language: node_js

node_js:
  - 10.15.0
  - node

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

install: true

script:
  - 'if [ $TEST_SUITE = "verify" ]; then yarn run verify; fi'

env:
  matrix:
    - TEST_SUITE=verify

matrix:
  include:
    - os: linux
      node_js: 10.15.0
      env: TEST_SUITE=verify
