# https://github.com/circleci/cci-demo-react/blob/master/.circleci/config.yml
# https://medium.com/@knowbody/circleci-and-zeits-now-sh-c9b7eebcd3c1

version: 2
jobs:
  build:
    docker: 
      - image: node:10.15.0
    steps:
      - checkout
      - run: 
          name: Environment
          command: env && pwd && echo $PATH && ls -alR
      - run: 
          name: Install
          command: yarn install
      - run: 
          name: List Installation
          command: npm list && ls -lR .
      - run: 
          name: Verify (lint and test)
          command: yarn verify
